### ISSUE TITLE
Consider making constructor writable

### ISSUE THREAD

**Issue by blakeembrey** [julien-f/js-make-error#4]
It's a minor issue and it's completely reasonable if you wish to close this, but I run into a TypeError issue when running under `'use strict'` - more information in TypeScript since it's technically an issue there and not here: https://github.com/Microsoft/TypeScript/issues/6887. Basically, assignment to this property throw a TypeError under `'use strict'` because it takes shadowing into account even though it's a different object (just a part of the prototype).

**Comment by julien-f** [comment]
I will make it writable and configurable as it is the case for `Error.prototype.constructor` in v8 4.5.

**Comment by julien-f** [comment]
Published as v1.1.1. :)

**Comment by blakeembrey** [comment]
Thank you! :+1:
